//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ProyectoMercadoEntities : DbContext
    {
        public ProyectoMercadoEntities()
            : base("name=ProyectoMercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<PRODUCTOFRESCO> PRODUCTOFRESCO { get; set; }
        public DbSet<PRODUCTONOFRESCO> PRODUCTONOFRESCO { get; set; }
    
        public virtual int PROCEDURE_COMPRA(string pCID, Nullable<decimal> pCCANTIDAD)
        {
            var pCIDParameter = pCID != null ?
                new ObjectParameter("PCID", pCID) :
                new ObjectParameter("PCID", typeof(string));
    
            var pCCANTIDADParameter = pCCANTIDAD.HasValue ?
                new ObjectParameter("PCCANTIDAD", pCCANTIDAD) :
                new ObjectParameter("PCCANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_COMPRA", pCIDParameter, pCCANTIDADParameter);
        }
    }
}
