//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOFRESCO
    {
        public decimal PLU { get; set; }
        public decimal PESO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
    }
}
